#!/bin/env bash

input=$( yad --width=400 --height=400 \
             --borders=6 --center \
             --title='Add Button' \
             --window-icon=/usr/share/icons/ramallahos.svg \
             --form --field="Title:CE" \
                    --field="Tooltip:CE" \
                    --field="Command:CE" \
                    --field="Function:TXT" )

title=$( echo $input | awk -F "|" '{ print $1 }' )
tooltip=$( echo $input | awk -F "|" '{ print $2 }' )
cmd=$( echo $input | awk -F "|" '{ print $3 }' )
func=$( echo $input | awk -F "|" '{ print $4 }' )


if [[ $input != "||" ]] && [[ $title != "" ]] && [[ $func != "" ]] && [[ $cmd != "" ]] && [[ $tooltip != "" ]];
then
    sed -i "/<!---->/i \<div class='hover-text'><a href='$title' data-tooltip='top tooltip' data-placement='top' class='btn'>$title</a><span class='tooltip-text' id="top">$tooltip</span></div>" /usr/share/resources/ramallahos-tweak-tool/users.html
    sed -i "/eval \$\@/i \ $title\(\) \{\n$func\\n}\n" /usr/share/resources/ramallahos-tweak-tool/functions
    sed -i "/\#add-before/i \ $title\) bash $cmd ;;" /usr/share/resources/ramallahos-tweak-tool/users
    notify-send -a "RamallahOS Tweaks" -u low "Restart the App"
fi
