#!/bin/env bash

stdbuf -oL -eL yad  --width='900' --height='500' --borders=0 --center \
					--title='RamallahOS Tweak Tool' \
					--window-icon=/usr/share/icons/ramallahos.svg \
					--no-buttons --no-escape \
                    --html --uri="/usr/share/resources/ramallahos-tweak-tool/home.html"\
                    --print-uri 2>&1 \
| while read -r line; do
     case ${line##*/} in
      main) bash /usr/share/resources/ramallahos-tweak-tool/main  ;;
      users) bash /usr/share/resources/ramallahos-tweak-tool/users ;;
      *) echo "${line##*/}" ;;
     esac
done
